---
title: "VR Analyses Additional DVs"
author: "Katherine Mason"
date: "2025-08-31"
output: html_document
---

####################################### Prepare Data ####################################### 

```{r, Load Packages}

library(tidyverse)
library(readxl)
library(writexl)
library(openxlsx)
library(psych)
library(ltm)
library(Hmisc)
library(reticulate)
library(nlme)
library(ordinal)
library(carData)
library(car)
library(lme4)
library(lmerTest)
library(lmtest)
library(clubSandwich)
library(sandwich)
library(CR2)
library(lsmeans)
library(stats)
library(sjPlot)
library(sjmisc)
library(ggplot2)
library(glmmTMB) 
library(MASS)
library(broom) 
library(knitr)
library(tools)
library(sjstats)
library(effectsize)
library(pscl)
library(logistf)
library(lavaan)
library(kableExtra)
library(boot)
library(margins)
library(purrr)
library(xtable)
library(gt) 
library(weights)
library(mediation)
library(QuantPsyc)
library(lm.beta)
library(parameters)
library(esc)
library(corrplot)
library(ivreg)
library(estimatr)

```

```{r, Load and Prepare Data}

df <- read.csv("Voter_Reg_STRICT.csv")
head(df)

nrow(df)

zdf <- read.csv("Voter_Reg_STRICT_STANDARDIZED.csv")
head(zdf)

nrow(zdf)

## Prepare variables ##

# Set reference level as the control conditon
df$condition <- relevel(as.factor(df$condition), ref = "ControlCondition")

zdf$condition <- relevel(as.factor(zdf$condition), ref = "ControlCondition")

# Make sure link click, register, and vote variables are factors for regressions
df$linkClicked <- as.factor(df$linkClicked)
df$register <- as.factor(df$register)
df$vote <- as.factor(df$vote)

```

##############################################################################################
######################## Dual Mediations - Trust, Efficacy, and Norms ########################  
##############################################################################################

# Link Clicks

```{r, Dual Medation Link Clicks}

set.seed(1234)

# Only use complete data
df_med <- df %>%
  dplyr::select(linkClicked_n, condition, trust_agg_c, efficacy_c, 
                norms_c) %>%
  na.omit()

# Specify each path

# Mediator model trust
med_model_trust <- lm(trust_agg_c ~ condition, data = df_med)
summary(med_model_trust)

# Mediator model efficacy
med_model_efficacy <- lm(efficacy_c ~ condition, data = df_med)
summary(med_model_efficacy)

# Mediator model norms
med_model_norms <- lm(norms_c ~ condition, data = df_med)
summary(med_model_norms)

# Outcome model 
out_model <- lm(linkClicked_n ~ condition + trust_agg_c + efficacy_c + norms_c, data = df_med)
summary(out_model)

# Check for multi-collinearity between mediators
vif(out_model)

######### Mediations #########

# Only for those that had significant direct effects (after BH corrections)

### Correcting Misperceptions ###

# Correcting Misperceptions via trust
CM_trust <- mediation::mediate(
  model.m = med_model_trust,                
  model.y = out_model,               
  treat = "condition",            
  mediator = "trust_agg_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "CorrectingMisperceptions"
)
summary(CM_trust)

# Correcting Misperceptions via efficacy
CM_efficacy <- mediation::mediate(
  model.m = med_model_efficacy,                
  model.y = out_model,               
  treat = "condition",            
  mediator = "efficacy_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "CorrectingMisperceptions"
)
summary(CM_efficacy)

# Correcting Misperceptions via norms
CM_norms <- mediation::mediate(
  model.m = med_model_norms,                
  model.y = out_model,               
  treat = "condition",            
  mediator = "norms_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "CorrectingMisperceptions"
)
summary(CM_norms)

### Dynamic Norms ###

# Dynamic Norms via trust
DN_trust <- mediation::mediate(
  model.m = med_model_trust,                
  model.y = out_model,               
  treat = "condition",            
  mediator = "trust_agg_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "DynamicNorms"
)
summary(DN_trust)

# Dynamic Norms via efficacy
DN_efficacy <- mediation::mediate(
  model.m = med_model_efficacy,                
  model.y = out_model,               
  treat = "condition",            
  mediator = "efficacy_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "DynamicNorms"
)
summary(DN_efficacy)

# Dynamic Norms via norms
DN_norms <- mediation::mediate(
  model.m = med_model_norms,                
  model.y = out_model,               
  treat = "condition",            
  mediator = "norms_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "DynamicNorms"
)
summary(DN_norms)

### Escalating Commitment ###

# Escalating Commitment via trust
EC_trust <- mediation::mediate(
  model.m = med_model_trust,                
  model.y = out_model,               
  treat = "condition",            
  mediator = "trust_agg_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "EscalatingCommitment"
)
summary(EC_trust)

# Escalating Commitment via efficacy
EC_efficacy <- mediation::mediate(
  model.m = med_model_efficacy,                
  model.y = out_model,               
  treat = "condition",            
  mediator = "efficacy_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "EscalatingCommitment"
)
summary(EC_efficacy)

# Escalating Commitment via norms
EC_norms <- mediation::mediate(
  model.m = med_model_norms,                
  model.y = out_model,               
  treat = "condition",            
  mediator = "norms_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "EscalatingCommitment"
)
summary(EC_norms)

### Implementation Intentions ### 

# Implementation Intentions via trust
II_trust <- mediation::mediate(
  model.m = med_model_trust,                
  model.y = out_model,               
  treat = "condition",            
  mediator = "trust_agg_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "ImplementationIntentions"
)
summary(II_trust)

# Implementation Intentions via efficacy
II_efficacy <- mediation::mediate(
  model.m = med_model_efficacy,                
  model.y = out_model,               
  treat = "condition",            
  mediator = "efficacy_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "ImplementationIntentions"
)
summary(II_efficacy)

# Implementation Intentions via norms
II_norms <- mediation::mediate(
  model.m = med_model_norms,                
  model.y = out_model,               
  treat = "condition",            
  mediator = "norms_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "ImplementationIntentions"
)
summary(II_norms)

### System Justification ### 

# System Justification via trust
SJ_trust <- mediation::mediate(
  model.m = med_model_trust,                
  model.y = out_model,               
  treat = "condition",            
  mediator = "trust_agg_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "SystemJustification"
)
summary(SJ_trust)

# System Justification via efficacy
SJ_efficacy <- mediation::mediate(
  model.m = med_model_efficacy,                
  model.y = out_model,               
  treat = "condition",            
  mediator = "efficacy_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "SystemJustification"
)
summary(SJ_efficacy)

# System Justification via norms
SJ_norms <- mediation::mediate(
  model.m = med_model_norms,                
  model.y = out_model,               
  treat = "condition",            
  mediator = "norms_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "SystemJustification"
)
summary(SJ_norms)

```

```{r, Print Dual Medation Link Clicks}

# Escalating Commitment 
cat("\n--------------------------------- Escalating Commitment via Trust ---------------------------------\n")
print(summary(EC_trust))
print.xtable(format_mediation_output(EC_trust), include.rownames = FALSE)

cat("\n--------------------------------- Escalating Commitment via Efficacy ---------------------------------\n")
print(summary(EC_efficacy))
print.xtable(format_mediation_output(EC_efficacy), include.rownames = FALSE)

cat("\n--------------------------------- Escalating Commitment via Norms ---------------------------------\n")
print(summary(EC_norms))
print.xtable(format_mediation_output(EC_norms), include.rownames = FALSE)

##

# System Justification
cat("\n--------------------------------- System Justification via Trust ---------------------------------\n")
print(summary(SJ_trust))
print.xtable(format_mediation_output(SJ_trust), include.rownames = FALSE)

cat("\n--------------------------------- System Justification via Efficacy ---------------------------------\n")
print(summary(SJ_efficacy))
print.xtable(format_mediation_output(SJ_efficacy), include.rownames = FALSE)

cat("\n--------------------------------- System Justification via Norms ---------------------------------\n")
print(summary(SJ_norms))
print.xtable(format_mediation_output(SJ_norms), include.rownames = FALSE)

##

# Dynamic Norms
cat("\n--------------------------------- Dynamic Norms via Trust ---------------------------------\n")
print(summary(DN_trust))
print.xtable(format_mediation_output(DN_trust), include.rownames = FALSE)

cat("\n--------------------------------- Dynamic Norms via Efficacy ---------------------------------\n")
print(summary(DN_efficacy))
print.xtable(format_mediation_output(DN_efficacy), include.rownames = FALSE)

cat("\n--------------------------------- Dynamic Norms via Norms ---------------------------------\n")
print(summary(DN_norms))
print.xtable(format_mediation_output(DN_norms), include.rownames = FALSE)

##

# Correcting Misperceptions
cat("\n--------------------------------- Correcting Mispercptions via Trust ---------------------------------\n")
print(summary(CM_trust))
print.xtable(format_mediation_output(CM_trust), include.rownames = FALSE)

cat("\n--------------------------------- Correcting Mispercptions via Efficacy ---------------------------------\n")
print(summary(CM_efficacy))
print.xtable(format_mediation_output(CM_efficacy), include.rownames = FALSE)

cat("\n--------------------------------- Correcting Mispercptions via Norms ---------------------------------\n")
print(summary(CM_norms))
print.xtable(format_mediation_output(CM_norms), include.rownames = FALSE)

##

# Implementation Intentions
cat("\n--------------------------------- Implementation Intentions via Trust ---------------------------------\n")
print(summary(II_trust))
print.xtable(format_mediation_output(II_trust), include.rownames = FALSE)

cat("\n--------------------------------- Implementation Intentions via Efficacy ---------------------------------\n")
print(summary(II_efficacy))
print.xtable(format_mediation_output(II_efficacy), include.rownames = FALSE)

cat("\n--------------------------------- Implementation Intentions via Norms ---------------------------------\n")
print(summary(II_norms))
print.xtable(format_mediation_output(II_norms), include.rownames = FALSE)

```

```{r, Sensitivity Analyses Link Clicks}

# Use for significant indirect effects

# Escalating Commitment --> link clicks via efficacy
EC_efficacy_sense <- medsens(EC_efficacy, rho.by = 0.05)
summary(EC_efficacy_sense)
plot(EC_efficacy_sense)

# System Justification --> link clicks via efficacy
SJ_efficacy_sense <- medsens(SJ_efficacy, rho.by = 0.05)
summary(SJ_efficacy_sense)
plot(SJ_efficacy_sense)

# Dynamic Norms --> link clicks via efficacy
DN_efficacy_sense <- medsens(SJ_efficacy, rho.by = 0.05)
summary(DN_efficacy_sense)
plot(DN_efficacy_sense)

```

# Voting Intentions

```{r, Dual Medation Voting Intentions}

# Only use complete data
df_med2 <- df %>%
  dplyr::select(voteInt, condition, trust_agg_c, efficacy_c, 
                norms_c) %>%
  na.omit()

# Specify each path

# Mediator model trust
med_model_trust2 <- lm(trust_agg_c ~ condition, data = df_med2)
summary(med_model_trust2)

# Mediator model efficacy
med_model_efficacy2 <- lm(efficacy_c ~ condition, data = df_med2)
summary(med_model_efficacy2)

# Mediator model norms
med_model_norms2 <- lm(norms_c ~ condition, data = df_med2)
summary(med_model_norms2)

# Outcome model 
out_model2 <- lm(voteInt ~ condition + trust_agg_c + efficacy_c + norms_c, 
                 data = df_med2)
summary(out_model2)

# Check for multi-collinearity between mediators
vif(out_model2)

######### Mediations #########

### Correcting Misperceptions ###

# Correcting Misperceptions via trust
CM_trust2 <- mediation::mediate(
  model.m = med_model_trust2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "trust_agg_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "CorrectingMisperceptions"
)
summary(CM_trust2)

# Correcting Misperceptions via efficacy
CM_efficacy2 <- mediation::mediate(
  model.m = med_model_efficacy2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "efficacy_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "CorrectingMisperceptions"
)
summary(CM_efficacy2)

# Correcting Misperceptions via norms
CM_norms2 <- mediation::mediate(
  model.m = med_model_norms2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "norms_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "CorrectingMisperceptions"
)
summary(CM_norms2)

### Distrust Salience ###

# Distrust Salience via trust
DS_trust2 <- mediation::mediate(
  model.m = med_model_trust2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "trust_agg_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "DistrustSalience"
)
summary(DS_trust2)

# Distrust Salience via efficacy
DS_efficacy2 <- mediation::mediate(
  model.m = med_model_efficacy2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "efficacy_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "DistrustSalience"
)
summary(DS_efficacy2)

# Distrust Salience via norms
DS_norms2 <- mediation::mediate(
  model.m = med_model_norms2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "norms_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "DistrustSalience"
)

summary(DS_norms2)

### Dynamic Norms ###

# Dynamic Norms via trust
DN_trust2 <- mediation::mediate(
  model.m = med_model_trust2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "trust_agg_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "DynamicNorms"
)
summary(DN_trust2)

# Dynamic Norms via efficacy
DN_efficacy2 <- mediation::mediate(
  model.m = med_model_efficacy2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "efficacy_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "DynamicNorms"
)
summary(DN_efficacy2)

# Dynamic Norms via norms
DN_norms2 <- mediation::mediate(
  model.m = med_model_norms2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "norms_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "DynamicNorms"
)
summary(DN_norms2)

### Escalating Commitment ###

# Escalating Commitment via trust
EC_trust2 <- mediation::mediate(
  model.m = med_model_trust2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "trust_agg_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "EscalatingCommitment"
)
summary(EC_trust2)

# Escalating Commitment via efficacy
EC_efficacy2 <- mediation::mediate(
  model.m = med_model_efficacy2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "efficacy_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "EscalatingCommitment"
)
summary(EC_efficacy2)

# Escalating Commitment via norms
EC_norms2 <- mediation::mediate(
  model.m = med_model_norms2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "norms_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "EscalatingCommitment"
)
summary(EC_norms2)

### Implementation Intentions ### 

# Implementation Intentions via trust
II_trust2 <- mediation::mediate(
  model.m = med_model_trust2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "trust_agg_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "ImplementationIntentions"
)
summary(II_trust2)

# Implementation Intentions via efficacy
II_efficacy2 <- mediation::mediate(
  model.m = med_model_efficacy2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "efficacy_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "ImplementationIntentions"
)
summary(II_efficacy2)

# Implementation Intentions via norms
II_norms2 <- mediation::mediate(
  model.m = med_model_norms2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "norms_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "ImplementationIntentions"
)
summary(II_norms2)

### Moral Reasons ###

# Moral Reasons via trust
MR_trust2 <- mediation::mediate(
  model.m = med_model_trust2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "trust_agg_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "MoralReasons"
)
summary(MR_trust2)

# Moral Reasons via efficacy
MR_efficacy2 <- mediation::mediate(
  model.m = med_model_efficacy2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "efficacy_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "MoralReasons"
)
summary(MR_efficacy2)

# Moral Reasons via norms
MR_norms2 <- mediation::mediate(
  model.m = med_model_norms2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "norms_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "MoralReasons"
)
summary(MR_norms2)

### Personal Importance ###

# Personal Importance via trust
PI_trust2 <- mediation::mediate(
  model.m = med_model_trust2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "trust_agg_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "PersonalImportance"
)
summary(PI_trust2)

# Personal Importance via efficacy
PI_efficacy2 <- mediation::mediate(
  model.m = med_model_efficacy2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "efficacy_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "PersonalImportance"
)
summary(PI_efficacy2)

# Personal Importance via norms
PI_norms2 <- mediation::mediate(
  model.m = med_model_norms2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "norms_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "PersonalImportance"
)
summary(PI_norms2)

### System Justification ### 

# System Justification via trust
SJ_trust2 <- mediation::mediate(
  model.m = med_model_trust2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "trust_agg_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "SystemJustification"
)
summary(SJ_trust2)

# System Justification via efficacy
SJ_efficacy2 <- mediation::mediate(
  model.m = med_model_efficacy2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "efficacy_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "SystemJustification"
)
summary(SJ_efficacy2)

# System Justification via norms
SJ_norms2 <- mediation::mediate(
  model.m = med_model_norms2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "norms_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "SystemJustification"
)
summary(SJ_norms2)

### Personal Importance ### 

# Personal Importance via trust
PI_trust2 <- mediation::mediate(
  model.m = med_model_trust2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "trust_agg_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "PersonalImportance"
)
summary(PI_trust2)

# Personal Importance via efficacy
PI_efficacy2 <- mediation::mediate(
  model.m = med_model_efficacy2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "efficacy_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "PersonalImportance"
)
summary(PI_efficacy2)

# Personal Importance via norms
PI_norms2 <- mediation::mediate(
  model.m = med_model_norms2,                
  model.y = out_model2,               
  treat = "condition",            
  mediator = "norms_c",          
  boot = TRUE,                   
  sims = 1000,
  control.value = "ControlCondition",      
  treat.value = "PersonalImportance"
)
summary(PI_norms2)

```

```{r, Print Dual Medation Voting Intentions}

# Print those that had a significant direct effect (which was all of them)

### Escalating Commitment ##
cat("\n--------------------------------- Escalating Commitment via Trust ---------------------------------\n")
print(summary(EC_trust2))
print.xtable(format_mediation_output(EC_trust2), include.rownames = FALSE)

cat("\n--------------------------------- Escalating Commitment via Efficacy ---------------------------------\n")
print(summary(EC_efficacy2))
print.xtable(format_mediation_output(EC_efficacy2), include.rownames = FALSE)

cat("\n--------------------------------- Escalating Commitment via Norms ---------------------------------\n")
print(summary(EC_norms2))
print.xtable(format_mediation_output(EC_norms2), include.rownames = FALSE)

### Distrust Salience ### 
cat("\n--------------------------------- Distrust Salience via Trust ---------------------------------\n")
print(summary(DS_trust2))
print.xtable(format_mediation_output(DS_trust2), include.rownames = FALSE)

cat("\n--------------------------------- Distrust Salience via Efficacy ---------------------------------\n")
print(summary(DS_efficacy2))
print.xtable(format_mediation_output(DS_efficacy2), include.rownames = FALSE)

cat("\n--------------------------------- Distrust Salience via Norms ---------------------------------\n")
print(summary(DS_norms2))
print.xtable(format_mediation_output(DS_norms2), include.rownames = FALSE)

### System Justification ###  
cat("\n--------------------------------- System Justification via Trust ---------------------------------\n")
print(summary(SJ_trust2))
print.xtable(format_mediation_output(SJ_trust2), include.rownames = FALSE)

cat("\n--------------------------------- System Justification via Efficacy ---------------------------------\n")
print(summary(SJ_efficacy2))
print.xtable(format_mediation_output(SJ_efficacy2), include.rownames = FALSE)

cat("\n--------------------------------- System Justification via Norms ---------------------------------\n")
print(summary(SJ_norms2))
print.xtable(format_mediation_output(SJ_norms2), include.rownames = FALSE)

### Personal Importance ###
cat("\n--------------------------------- Personal Importance via Trust ---------------------------------\n")
print(summary(PI_trust2))
print.xtable(format_mediation_output(PI_trust2), include.rownames = FALSE)

cat("\n--------------------------------- Personal Importance via Efficacy ---------------------------------\n")
print(summary(PI_efficacy2))
print.xtable(format_mediation_output(PI_efficacy2), include.rownames = FALSE)

cat("\n--------------------------------- Personal Importance via Norms ---------------------------------\n")
print(summary(PI_norms2))
print.xtable(format_mediation_output(PI_norms2), include.rownames = FALSE)

### Moral Reasons ###
cat("\n--------------------------------- Moral Reasons via Trust ---------------------------------\n")
print(summary(MR_trust2))
print.xtable(format_mediation_output(MR_trust2), include.rownames = FALSE)

cat("\n--------------------------------- Moral Reasons via Efficacy ---------------------------------\n")
print(summary(MR_efficacy2))
print.xtable(format_mediation_output(MR_efficacy2), include.rownames = FALSE)

cat("\n--------------------------------- Moral Reasons via Norms ---------------------------------\n")
print(summary(MR_norms2))
print.xtable(format_mediation_output(MR_norms2), include.rownames = FALSE)

### Dynamic Norms ###
cat("\n--------------------------------- Dynamic Norms via Trust ---------------------------------\n")
print(summary(DN_trust2))
print.xtable(format_mediation_output(DN_trust2), include.rownames = FALSE)

cat("\n--------------------------------- Dynamic Norms via Efficacy ---------------------------------\n")
print(summary(DN_efficacy2))
print.xtable(format_mediation_output(DN_efficacy2), include.rownames = FALSE)

cat("\n--------------------------------- Dynamic Norms via Norms ---------------------------------\n")
print(summary(DN_norms2))
print.xtable(format_mediation_output(DN_norms2), include.rownames = FALSE)

### Implementation Intentions ###
cat("\n--------------------------------- Implementation Intentions via Trust ---------------------------------\n")
print(summary(II_trust2))
print.xtable(format_mediation_output(II_trust2), include.rownames = FALSE)

cat("\n--------------------------------- Implementation Intentions via Efficacy ---------------------------------\n")
print(summary(II_efficacy2))
print.xtable(format_mediation_output(II_efficacy2), include.rownames = FALSE)

cat("\n--------------------------------- Implementation Intentions via Norms ---------------------------------\n")
print(summary(II_norms2))
print.xtable(format_mediation_output(II_norms2), include.rownames = FALSE)

#### Correcting Mispercptions ###
cat("\n--------------------------------- Correcting Mispercptions via Trust ---------------------------------\n")
print(summary(CM_trust2))
print.xtable(format_mediation_output(CM_trust2), include.rownames = FALSE)

cat("\n--------------------------------- Correcting Mispercptions via Efficacy ---------------------------------\n")
print(summary(CM_efficacy2))
print.xtable(format_mediation_output(CM_efficacy2), include.rownames = FALSE)

cat("\n--------------------------------- Correcting Mispercptions via Norms ---------------------------------\n")
print(summary(CM_norms2))
print.xtable(format_mediation_output(CM_norms2), include.rownames = FALSE)

```

```{r, Sensitivity Analyses Voting Intentions}

# Use for significant indirect effects

# Escalating Commitment --> voting intentions 

# Via trust
EC_trust2_sense <- medsens(EC_trust2, rho.by = 0.05)
summary(EC_trust2_sense)
plot(EC_trust2_sense)

# Via efficacy
EC_efficacy2_sense <- medsens(EC_efficacy2, rho.by = 0.05)
summary(EC_efficacy2_sense)
plot(EC_efficacy2_sense)


# Distrust Salience --> voting intentions 

# Via trust
DS_trust2_sense <- medsens(DS_trust2, rho.by = 0.05)
summary(DS_trust2_sense)
plot(DS_trust2_sense)

# Via efficacy
DS_efficacy2_sense <- medsens(DS_efficacy2, rho.by = 0.05)
summary(DS_efficacy2_sense)
plot(DS_efficacy2_sense)

# Via norms
DS_norms2_sens <- medsens(DS_norms2, rho.by = 0.05)
summary(DS_norms2_sens)
plot(DS_norms2_sens)


# System Justification --> voting intentions 

# Via trust
SJ_trust2_sens <- medsens(SJ_trust2, rho.by = 0.05)
summary(SJ_trust2_sens)
plot(SJ_trust2_sens)

# Via efficacy
SJ_efficacy2_sens <- medsens(SJ_efficacy2, rho.by = 0.05)
summary(SJ_efficacy2_sens)
plot(SJ_efficacy2_sens)


# Personal Importance --> voting intentions

# Via trust
PI_trust2_sens <- medsens(PI_trust2, rho.by = 0.05)
summary(PI_trust2_sens)
plot(PI_trust2_sens)

# Via efficacy
PI_efficacy2_sens <- medsens(PI_efficacy2, rho.by = 0.05)
summary(PI_efficacy2_sens)
plot(PI_efficacy2_sens)

# Moral Reasons --> voting intentions

# Via trust
MR_trust2_sens <- medsens(MR_trust2, rho.by = 0.05)
summary(MR_trust2_sens)
plot(MR_trust2_sens)

# Via efficacy
MR_efficacy2_sens <- medsens(MR_efficacy2, rho.by = 0.05)
summary(MR_efficacy2_sens)
plot(MR_efficacy2_sens)

# Dynamic Norms --> voting intentions

# Via trust
DN_trust2_sens <- medsens(DN_trust2, rho.by = 0.05)
summary(DN_trust2_sens)
plot(DN_trust2_sens)

# Via efficacy
DN_efficacy2_sens <- medsens(DN_efficacy2, rho.by = 0.05)
summary(DN_efficacy2_sens)
plot(DN_efficacy2_sens)


# Implementation Intentions

# Via trust
II_trust2_sens <- medsens(II_trust2, rho.by = 0.05)
summary(II_trust2_sens)
plot(II_trust2_sens)

```

###############################################################################################  
################################ Instrumental Variable Analysis ############################### 
###############################################################################################  

```{r, Instrumental variable analysis link clicks and registration}

# Estimate the effect of link clicks on registration, using condition as the instrument for link clicks
# Register = DV
# Link clicks = endogenous variable 
# Condition = instrument 

iv_model_register <- ivreg(register_n ~ linkClicked_n | condition, data = df)
summary(iv_model_register)

iv_model_register_robust <- coeftest(iv_model_register, vcov = vcovHC(iv_model_register, type = "HC3"))
iv_model_register_robust

```

```{r, Instrumental variable analysis intentions and voting}

iv_model_vote <- ivreg(vote_n ~ voteInt | condition, data = df)
summary(iv_model_vote)

iv_model_vote_robust <- coeftest(iv_model_vote, vcov = vcovHC(iv_model_vote, type = "HC3"))
iv_model_vote_robust

```
